Ready for review!
LaraBug/larabug-app pull request #16
Opened 2021-04-28 12:41 UTC by SebastiaanKloos

![CleanShot 2021-04-28 at 14 40 37](https://user-images.githubusercontent.com/6506510/116405328-d1b28900-a82f-11eb-8b7e-b91f8b57836e.png)

2021-04-28 14:04 UTC, Glennmen approved these changes

2021-04-28 14:14 UTC, Cannonb4ll commented
Works really well, however, wouldn't it cool if we extend this a tad more with the new `Password` Rule that has just been added to the latest Laravel version?

I recommend setting the validation rule too:

```php
            'password' => [
                'required',
                'confirmed',
                Password::min(8)
                    ->letters()
                    ->numbers()
                    ->uncompromised()
            ]
```

2021-04-28 14:32 UTC, Glennmen commented
@Cannonb4ll Cool idea! Maybe also set a threshold for `uncompromised()` 🤔 treat it as compromised only if it was found +3 times? To filter out commonly used passwords.

2021-05-02 15:40 UTC, SebastiaanKloos commented
@Cannonb4ll @Glennmen I've added the rules as suggested. Also, the registration form uses the new validation rules!

2021-05-02 15:44 UTC, merged

2021-05-02 15:47 UTC, Glennmen requested changes

2021-05-02 15:47 UTC, Glennmen commented on app/Http/Controllers/Profile/ProfileController.php
> +        if (! Hash::check($request->current, $request->user()->password)) {
Is this actually needed? Can't it be done with validation rules? https://laravel.com/docs/8.x/validation#rule-password

2021-05-02 15:49 UTC, SebastiaanKloos commented on app/Http/Controllers/Profile/ProfileController.php
> +        if (! Hash::check($request->current, $request->user()->password)) {
@Glennmen don't really know... I'll try it soon